#!/usr/bin/env python3
import sys
import json
import time
import re
from datetime import datetime, timezone
from pathlib import Path

def get_workspace_root() -> Path:
    return Path(__file__).resolve().parents[2]

def run_check():
    start_time = time.perf_counter_ns()
    workspace = get_workspace_root()
    arch_dir = workspace / "architecture"
    
    violations = []
    
    # Matches [text](path)
    link_pattern = re.compile(r'\[([^\]]+)\]\(([^)]+)\)')
    
    if arch_dir.exists():
        for md_file in arch_dir.rglob("*.md"):
            try:
                with open(md_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                lines = content.splitlines()
                for i, line in enumerate(lines):
                    for match in link_pattern.finditer(line):
                        link_path = match.group(2).strip()
                        
                        # Ignore external links, mailto, absolute files generally generated by AI
                        if link_path.startswith(("http://", "https://", "mailto:", "file://")):
                            continue
                            
                        # Remove fragment hash
                        clean_path = link_path.split("#")[0]
                        if not clean_path:
                            continue # Hash link only, points to same file
                            
                        target_path = (md_file.parent / clean_path).resolve()
                        
                        if not target_path.exists():
                            violations.append({
                                "file": str(md_file.relative_to(workspace)),
                                "line": i + 1,
                                "broken_link": link_path,
                                "resolved_path_attempt": str(target_path)
                            })
            except Exception:
                pass
                
    duration_ms = (time.perf_counter_ns() - start_time) // 1_000_000
    status = "ready" if not violations else "error"
    message = "No broken architecture links" if not violations else f"{len(violations)} broken links detected"
    
    report = {
        "category": "architecture_links",
        "status": status,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "message": message,
        "actionable": bool(violations),
        "remediation": "Fix relative paths in architecture documentation" if violations else None,
        "results": {
            "violations": violations
        },
        "metrics": {
            "duration_ms": duration_ms
        }
    }
    
    return report

if __name__ == "__main__":
    try:
        report = run_check()
        print(json.dumps(report, sort_keys=True))
        sys.exit(0 if report["status"] == "ready" else 1)
    except Exception as e:
        fallback = {
            "category": "architecture_links",
            "status": "error",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "message": "Critical failure in architecture link validator",
            "actionable": True,
            "remediation": "Check architecture_link_validator.py logic",
            "results": {"error": str(e)}
        }
        print(json.dumps(fallback, sort_keys=True))
        sys.exit(1)
